- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Run bot docker container
      docker_container:
        name: metro-2022-bot
        image: twobrowin/ru-cheque-google-spread-sheets-bot:1.0
        state: started
        detach: yes
        restart: yes
        recreate: yes
        env:
          TZ: "Europe/Moscow"
          
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"
