- hosts: all
  tags:
    - run_docker
  vars_files:
    - secrets.yaml
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Run bot docker service
      docker_swarm_service:
        name: ru-cheque-google-spread-sheets-bot
        image: twobrowin/ru-cheque-google-spread-sheets-bot:1.0.2
        env:
          TZ: "Europe/Moscow"
          BOT_TOKEN: "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"
